### ISSUE TITLE
Tribe Overview Rank display 

### ISSUE THREAD

**Issue by djbears32** [VMormoris/tw2-stats#1]
Currently the tribe rank on the tribe overview page seems to be backwards. 
Possible Fixes:

1. Reverse the number layout for the graph
2. Remove Decimal numbers rank can only be whole number

**Comment by VMormoris** [comment]
Yes I agree the current state of the ranking graph seems counterintuitive. The same can be also said about the player ranking graph.

Both fixes you mention would probably make the graph look much better. So feel free to change them and make and a pull request if you like.

**Comment by VMormoris** [comment]
I closed this issue since I made both fixes that you suggested for both tribes and players.
If you have any other suggestions please don't hesitate to open an other issue
