### ISSUE TITLE
World Overview 

### ISSUE THREAD

**Issue by djbears32** [VMormoris/tw2-stats#2]
Create an overview page for each world that shows different items 

1. Smaller table of recent conquers that links to main conquest table
2. Include line graph of all current tribes with a different color showing rank change as a whole
3.  Top 5 Tribe 
4. Top 5 players
5. Show daily achievements (Tribe/Player) with calculated stats since they are already being pulled 
6.

**Comment by VMormoris** [comment]
Creating an overview page was on of the things I also wanted to add at some point. 

All the suggestions you made sound great to me. But unfortunately 5 is not possible currently. The database doesn't store any data regarding player's or tribe's achievements. 

The game's current API doesn't allow me to ask for the achievements of multiple tribes or players at once.
I'm hopping that the new World API that was announced with the last update will make something like that possible. But that remains to be seen when it is published.

**Comment by VMormoris** [comment]
Resolve with Pull Request #6. You can see how it looks at: [en69 - tw2 stats](https://tw2-stats.com/en69)

I'm closing this issue.
If you have any other suggestions please don't hesitate to open another issue
